version: "3"
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "8080:80"
    mysql:
      restart: always
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        restart: always
    python:
      image: python
